# Generated by Django 4.2.10 on 2025-06-05 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='Order Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('billing_first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('billing_last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('billing_company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('billing_address', models.TextField(verbose_name='Address')),
                ('billing_city', models.CharField(max_length=100, verbose_name='City')),
                ('billing_postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('billing_country', models.CharField(default='Georgia', max_length=100, verbose_name='Country')),
                ('billing_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('different_shipping', models.BooleanField(default=False, verbose_name='Different Shipping Address')),
                ('shipping_first_name', models.CharField(blank=True, max_length=100, verbose_name='Shipping First Name')),
                ('shipping_last_name', models.CharField(blank=True, max_length=100, verbose_name='Shipping Last Name')),
                ('shipping_company', models.CharField(blank=True, max_length=100, verbose_name='Shipping Company')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='Shipping City')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Shipping Postal Code')),
                ('shipping_country', models.CharField(blank=True, max_length=100, verbose_name='Shipping Country')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, verbose_name='Shipping Phone')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Cost')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('order_status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Order Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('order_notes', models.TextField(blank=True, verbose_name='Order Notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='GEL', max_length=3, verbose_name='Currency')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='Card Last 4 Digits')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='Card Brand')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('gateway_response', models.TextField(blank=True, verbose_name='Gateway Response')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_model', models.CharField(max_length=50, verbose_name='Product Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
